/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SlotTestA {
    }
    interface SlotTestB {
        "toggleContent": () => Promise<void>;
    }
    interface SlotTestC {
        "toggleContent": () => Promise<void>;
    }
}
declare global {
    interface HTMLSlotTestAElement extends Components.SlotTestA, HTMLStencilElement {
    }
    var HTMLSlotTestAElement: {
        prototype: HTMLSlotTestAElement;
        new (): HTMLSlotTestAElement;
    };
    interface HTMLSlotTestBElement extends Components.SlotTestB, HTMLStencilElement {
    }
    var HTMLSlotTestBElement: {
        prototype: HTMLSlotTestBElement;
        new (): HTMLSlotTestBElement;
    };
    interface HTMLSlotTestCElement extends Components.SlotTestC, HTMLStencilElement {
    }
    var HTMLSlotTestCElement: {
        prototype: HTMLSlotTestCElement;
        new (): HTMLSlotTestCElement;
    };
    interface HTMLElementTagNameMap {
        "slot-test-a": HTMLSlotTestAElement;
        "slot-test-b": HTMLSlotTestBElement;
        "slot-test-c": HTMLSlotTestCElement;
    }
}
declare namespace LocalJSX {
    interface SlotTestA {
    }
    interface SlotTestB {
    }
    interface SlotTestC {
    }
    interface IntrinsicElements {
        "slot-test-a": SlotTestA;
        "slot-test-b": SlotTestB;
        "slot-test-c": SlotTestC;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "slot-test-a": LocalJSX.IntrinsicElements["slot-test-a"] & JSXBase.HTMLAttributes<HTMLSlotTestAElement>;
            "slot-test-b": LocalJSX.IntrinsicElements["slot-test-b"] & JSXBase.HTMLAttributes<HTMLSlotTestBElement>;
            "slot-test-c": LocalJSX.IntrinsicElements["slot-test-c"] & JSXBase.HTMLAttributes<HTMLSlotTestCElement>;
        }
    }
}
